# Generated by Django 2.0.7 on 2018-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('nationality', models.CharField(max_length=255)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=255)),
                ('appearances', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('yellow_cards', models.PositiveIntegerField()),
                ('red_cards', models.PositiveIntegerField()),
                ('shots_per_game', models.DecimalField(decimal_places=2, max_digits=5)),
                ('key_passes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
