# Generated by Django 2.0.7 on 2018-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadmember',
            name='number',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
    ]
